### ISSUE TITLE
[ALL] 모모 서비스 홍보

### ISSUE THREAD

**Issue by kyukong** [woowacourse-teams/2022-momo#366]
## 🛠 사전 준비 작업
- 자체 QA 진행하여 발생한 버그 해결
- DB 의 변경사항 적용
- DB 데이터 삭제 (논의 후 진행)
- [구글 폼](https://docs.google.com/forms/d/13UaeKLMqz4n-O533gxJER1NwWDHWL6rd9fw7d9nIAPc/edit) 제작
- 기프티콘 준비

## 🎉 모모 서비스 홍보
- Slack 에 모모 서비스 홍보 후 구글 폼으로 피드백 접수

**Comment by Seongwon97** [comment]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/57744251/196374696-ece807a5-d32c-480f-8192-5fa2d2658756.png">
