### ISSUE TITLE
[ALL]  마감일이 지나지 않아도 참여자 정원이 가득차면 수정/삭제할 수 없는 현상

### ISSUE THREAD

**Issue by sinb57** [woowacourse-teams/2022-momo#373]
## 버그가 발생한 기능
모임의 마감일이 지나지 않았음에도 참여자 정원이 가득차면, `모집 마감` 상태가 되어 수정/삭제가 불가능한 현상

## 버그 상황 재현
참여자 정원을 잘못 기재한 상태로 모임을 생성했고 이를 뒤늦게 알아차려 참여자 정원을 늘리고자 했으나,
이미 참여자 정원수만큼 크루들이 모임에 참여하여 `모집 마감` 상태가 되버리는 바람에 더이상 정보를 수정/삭제할 수 없음

**Comment by nbalance97** [comment]
BE 작업 완료했습니다! 참여자 정원 로직은 고려하지 않도록 변경하였습니다ㅎㅎ

프론트에서는 참여자가 가득 찬 경우에 대해서 참여자 관점에서 모임 참여 버튼이 disabled가 되도록 해주시면 될 거 같아요~
