### ISSUE TITLE
[FE] 모임 생성시 `Tab` 키를 통해 입력값을 이동하면 화면 레이아웃이 어긋하는 현상

### ISSUE THREAD

**Issue by sinb57** [woowacourse-teams/2022-momo#374]
## 버그가 발생한 기능
모임 생성시 `Tab` 키를 통해 입력값을 이동하면 화면 레이아웃이 어긋하는 현상

## 버그 상황 재현
모임 제목 작성 후 `Tab` 키 사용시 아래와 같이 레이아웃이 어긋난다.
<img width="70%" src="https://user-images.githubusercontent.com/22176552/192149202-5b336b79-4a0d-4213-8308-105a379d77cd.gif">

모임 기간 작성 후 `Tab` 키 사용시 아래와 같이 레이아웃이 어긋난다.
<img width="70%" src="https://user-images.githubusercontent.com/22176552/192149203-2908b7c7-1781-47bd-a8ce-49f00f36295d.gif">

이외 모임 생성의 모든 입력값에서 `Tab` 키 사용시 레이아웃이 어긋나는 현상이 발생한다.

**Comment by usageness** [comment]
생성 페이지 디자인 변경과 함께 해결.

- #471
