### ISSUE TITLE
[ALL] Member 와 Group 에 대한 제약조건 변경

### ISSUE THREAD

**Issue by kyukong** [woowacourse-teams/2022-momo#381]
### FE
- 사용자가 값을 입력했을 때 길이에 대한 검증 변경

### BE
- 서비스 로직에서 길이에 대한 검증 변경
- DB 테이블 제약조건 변경

## ✓ 모모 서비스 검증 조건
- 사용자 아이디 : `4` 자 이상 `50` 자 이하
- 사용자 이름 : `1` 자 이상 `20` 자 이하
- 모임 제목 : `1` 자 이상 `50` 자 이하
- 모임 설명 : `0` 자 이상 `1000` 자 이하

## ✓ DB 테이블 제약조건
- 사용자 이름 : `1` 자 이상 `36` 자 이하, Unique 조건 추가
  - 이전에 등록된 이름에 대한 Unique 처리 필요
  - 관련 PR : #379

**Comment by sinb57** [comment]
백엔드는 작업 완료했습니다~~~
