### ISSUE TITLE
[FE] react-query의 캐시로 인해 이전 데이터를 보여주던 에러 해결

### ISSUE THREAD

**Issue by LAH1203** [woowacourse-teams/2022-momo#531]
## 기능 상세

- 모임 목록을 업데이트하던 useEffect가 새로운 데이터를 받아오는 상황에서도 실행되어 이전 페이지의 모임 목록 데이터를 추가적으로 보여주는 에러 발견
- 모임 일정이 다른 모임 두 개 정도를 왔다갔다 하면 캐시로 인해 이전 모임의 일정이 보이는 에러 발견

## 추가 설명 (Optional)

- [x] 모임 목록 업데이트 useEffect의 디펜던시로 dataUpdatedAt 사용
- [x] 모임 상세 정보 쿼리 키 유니크화

**Comment by usageness** [comment]
`react-query` 의 `useQuery` 반환값 중 `dataUpdatedAt` 을 `isFetching` 대신 사용하면 data가 successful 하게 업데이트 된 시점에 useEffect를 실행할 수 있습니다~

![image](https://user-images.githubusercontent.com/28296575/198826905-3799d351-5676-4059-9ae5-432294bbf27b.png)

fetching에 실패했을 경우의 처리도 따로 해주면 좋긴 하겠군요...! 요건 다른 이슈에서 처리하면 될 것 같으니 TODO만 남겨주세욥
