### ISSUE TITLE
[BE] 찜하기 데이터 삭제 관련 이벤트 처리방식을 비동기로 변경

### ISSUE THREAD

**Issue by Seongwon97** [woowacourse-teams/2022-momo#548]
# ✨ 기능 상세
기존의 찜하기 이벤트 처리 방식은 동기처리가 되어 찜하기 데이터 삭제에 오류가 발생하면 모임 또는 회원 삭제 로직에 장애가 전파되어 전체 요청이 실패되는 상황이었다. 
이는 Group로직이 트랜잭션 측면에서 아직 Favorite에 장애 측면에서 의존하고 있다는 것을 의미한다.

이를 해결하기 위해 기존의 동기 처리방식의 이벤트를 비동기로 변경해보고자 한다.

# 🧾 작업한 내용
- [x] 이벤트 처리 방식을 동기 -> 비동기로 수정

**Comment by sinb57** [comment]
이벤트가 유실되거나 `찜하기` 데이터 삭제 트랜잭션이 실패하는 등 여러 상황을 고려했을 때, 이를 해결하는 전략도 고려해야 할 것 같습니다!! 조사한 바로는 Transactional Outbox Pattern을 흔히 사용한다고 하네용
